apiVersion: v2
name: evcc
description: Helm chart for EVCC (evcc.io)
home: https://evcc.io/
icon: https://jitsehijlkema.github.io/evcc-chart/evcc-logo.png
type: application
version: 1.0.31
appVersion: 0.210.0
keywords:
  - evcc
  - charging
  - ev
